"""alerta com unidade, mensagem e identidade unica

Duas colunas NOT NULL sem `server_default`, contra a regra da casa — e de propósito. A tabela
`alerta` nasceu no L1 e nunca teve uma linha: até o L11 não existia caminho de código que
inserisse um alerta. Não há valor de compatibilidade para inventar, e inventar um ("unidade 0",
mensagem vazia) seria pior: deixaria passar uma linha impossível.

Se algum dia esta migration rodar contra um banco com alertas, ela falha alto — que é o
comportamento certo, porque significa que a premissa acima deixou de valer.

Revision ID: 0517ef18c5d3
Revises: 66f40a59708d
Create Date: 2026-08-08 00:12:43.948194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0517ef18c5d3'
down_revision: Union[str, Sequence[str], None] = '66f40a59708d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mensagem', sa.String(length=400), nullable=False))
        batch_op.create_index(batch_op.f('ix_alerta_unidade_id'), ['unidade_id'], unique=False)
        batch_op.create_unique_constraint('uq_alerta_identidade', ['tipo', 'entidade', 'entidade_id'])
        batch_op.create_foreign_key(batch_op.f('fk_alerta_unidade_id_unidade'), 'unidade', ['unidade_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alerta_unidade_id_unidade'), type_='foreignkey')
        batch_op.drop_constraint('uq_alerta_identidade', type_='unique')
        batch_op.drop_index(batch_op.f('ix_alerta_unidade_id'))
        batch_op.drop_column('mensagem')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
