"""assinatura por etapa do fluxo

Revision ID: 126544508b16
Revises: 13bcae197fe3
Create Date: 2026-08-07 13:43:14.148826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126544508b16'
down_revision: Union[str, Sequence[str], None] = '13bcae197fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    estado = sa.Enum(
        'RASCUNHO', 'VALIDACAO', 'ANALISE_SMS', 'APROVACAO', 'LIBERACAO', 'EM_EXECUCAO',
        'ENCERRADA', 'ARQUIVADA', 'SUSPENSA', 'REJEITADA',
        name='estadopt', native_enum=False, length=40,
    )
    # Sem `server_default` de propósito: não existe etapa plausível para inventar num
    # documento já assinado, e chutar uma seria falsificar registro. A coluna entra nula e
    # vira NOT NULL em seguida — se houver assinatura anterior ao fluxo, isto falha alto, que
    # é o comportamento certo. Nenhuma pode existir: até o L5 não havia como assinar.
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_destino', estado, nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_assinatura_pt_papel_versao_pt'), type_='unique')

    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.alter_column('estado_destino', existing_type=estado, nullable=False)
        batch_op.create_unique_constraint('uq_assinatura_pt_etapa_versao', ['pt_id', 'estado_destino', 'versao_pt'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assinatura_pt_etapa_versao', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_assinatura_pt_papel_versao_pt'), ['pt_id', 'papel', 'versao_pt'])
        batch_op.drop_column('estado_destino')

    # ### end Alembic commands ###
