"""credencial e lotacao do usuario

Revision ID: 13bcae197fe3
Revises: 53e061bd6036
Create Date: 2026-08-07 09:25:17.397155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bcae197fe3'
down_revision: Union[str, Sequence[str], None] = '53e061bd6036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        # `server_default` é obrigatório aqui: a coluna é NOT NULL e a tabela já tem linhas.
        # Hash vazio não autentica ninguém — quem já existia fica sem acesso até receber senha.
        batch_op.add_column(
            sa.Column('senha_hash', sa.String(length=255), nullable=False, server_default='')
        )
        batch_op.add_column(sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_usuario_unidade_id'), ['unidade_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_usuario_unidade_id_unidade'), 'unidade', ['unidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuario_unidade_id_unidade'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuario_unidade_id'))
        batch_op.drop_column('ultimo_acesso')
        batch_op.drop_column('senha_hash')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
