"""modelo de dados inicial

Revision ID: 53e061bd6036
Revises: 
Create Date: 2026-08-07 09:06:32.584154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e061bd6036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('prazo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nivel_escalonamento', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'escalonado', 'resolvido', 'cancelado', name='statusalerta', native_enum=False, length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerta'))
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerta_prazo'), ['prazo'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerta_tipo'), ['tipo'], unique=False)

    op.create_table('modelo_pt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_trabalho', sa.Enum('trabalho_a_quente', 'espaco_confinado', 'trabalho_em_altura', 'icamento', 'intervencao_eletrica', 'inspecao_drone', name='tipotrabalho', native_enum=False, length=40), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('campos', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelo_pt')),
    sa.UniqueConstraint('tipo_trabalho', 'versao', name='uq_modelo_pt_tipo_trabalho_versao')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('identificador_operacional', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.Enum('plataforma_fixa', 'plataforma_semissubmersivel', 'fpso', 'navio', 'base_terrestre', name='tipounidade', native_enum=False, length=40), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidade')),
    sa.UniqueConstraint('identificador_operacional', name=op.f('uq_unidade_identificador_operacional'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=False),
    sa.Column('perfil', sa.Enum('requisitante', 'executante', 'tecnico_seguranca', 'area_responsavel', 'coordenador', 'oim', 'auditor', 'admin', name='perfilusuario', native_enum=False, length=40), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email')),
    sa.UniqueConstraint('matricula', name=op.f('uq_usuario_matricula'))
    )
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], name=op.f('fk_area_unidade_id_unidade'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_area')),
    sa.UniqueConstraint('unidade_id', 'codigo', name='uq_area_unidade_codigo')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_area_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('certificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('NR-10', 'NR-33', 'NR-34', 'NR-35', 'ANAC-RPAS', name='tipocertificacao', native_enum=False, length=40), nullable=False),
    sa.Column('numero', sa.String(length=60), nullable=False),
    sa.Column('emitida_em', sa.Date(), nullable=False),
    sa.Column('valida_ate', sa.Date(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_certificacao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificacao')),
    sa.UniqueConstraint('usuario_id', 'tipo', 'numero', name='uq_certificacao_usuario_tipo_numero')
    )
    with op.batch_alter_table('certificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificacao_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificacao_valida_ate'), ['valida_ate'], unique=False)

    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('criticidade', sa.Enum('baixa', 'media', 'alta', 'critica', name='criticidade', native_enum=False, length=40), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], name=op.f('fk_equipamento_area_id_area'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipamento')),
    sa.UniqueConstraint('tag', name=op.f('uq_equipamento_tag'))
    )
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipamento_area_id'), ['area_id'], unique=False)

    op.create_table('permissao_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo_trabalho', sa.Enum('trabalho_a_quente', 'espaco_confinado', 'trabalho_em_altura', 'icamento', 'intervencao_eletrica', 'inspecao_drone', name='tipotrabalho', native_enum=False, length=40), nullable=False),
    sa.Column('estado', sa.Enum('RASCUNHO', 'VALIDACAO', 'ANALISE_SMS', 'APROVACAO', 'LIBERACAO', 'EM_EXECUCAO', 'ENCERRADA', 'ARQUIVADA', 'SUSPENSA', 'REJEITADA', name='estadopt', native_enum=False, length=40), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('modelo_pt_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('requisitante_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('valida_de', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valida_ate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('perigos', sa.JSON(), nullable=False),
    sa.Column('controles', sa.JSON(), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], name=op.f('fk_permissao_trabalho_area_id_area')),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamento.id'], name=op.f('fk_permissao_trabalho_equipamento_id_equipamento')),
    sa.ForeignKeyConstraint(['modelo_pt_id'], ['modelo_pt.id'], name=op.f('fk_permissao_trabalho_modelo_pt_id_modelo_pt')),
    sa.ForeignKeyConstraint(['requisitante_id'], ['usuario.id'], name=op.f('fk_permissao_trabalho_requisitante_id_usuario')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], name=op.f('fk_permissao_trabalho_unidade_id_unidade')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissao_trabalho')),
    sa.UniqueConstraint('numero', name=op.f('uq_permissao_trabalho_numero')),
    sa.UniqueConstraint('uuid', name=op.f('uq_permissao_trabalho_uuid'))
    )
    with op.batch_alter_table('permissao_trabalho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissao_trabalho_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissao_trabalho_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissao_trabalho_requisitante_id'), ['requisitante_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissao_trabalho_unidade_id'), ['unidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissao_trabalho_valida_ate'), ['valida_ate'], unique=False)

    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('apr', 'aso', 'certificado', 'relatorio', 'foto', 'croqui', name='tipoanexo', native_enum=False, length=40), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho', sa.String(length=500), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('valido_ate', sa.Date(), nullable=True),
    sa.Column('enviado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuario.id'], name=op.f('fk_anexo_enviado_por_id_usuario')),
    sa.ForeignKeyConstraint(['pt_id'], ['permissao_trabalho.id'], name=op.f('fk_anexo_pt_id_permissao_trabalho'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anexo'))
    )
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexo_pt_id'), ['pt_id'], unique=False)

    op.create_table('assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.Enum('requisitante', 'executante', 'tecnico_seguranca', 'area_responsavel', 'coordenador', 'oim', name='papelassinatura', native_enum=False, length=40), nullable=False),
    sa.Column('versao_pt', sa.Integer(), nullable=False),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.Column('assinado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pt_id'], ['permissao_trabalho.id'], name=op.f('fk_assinatura_pt_id_permissao_trabalho'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_assinatura_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assinatura')),
    sa.UniqueConstraint('pt_id', 'papel', 'versao_pt', name='uq_assinatura_pt_papel_versao_pt')
    )
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assinatura_pt_id'), ['pt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinatura_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=True),
    sa.Column('ator_id', sa.Integer(), nullable=True),
    sa.Column('perfil_ator', sa.Enum('requisitante', 'executante', 'tecnico_seguranca', 'area_responsavel', 'coordenador', 'oim', 'auditor', 'admin', name='perfilusuario', native_enum=False, length=40), nullable=True),
    sa.Column('tipo_evento', sa.String(length=60), nullable=False),
    sa.Column('estado_origem', sa.Enum('RASCUNHO', 'VALIDACAO', 'ANALISE_SMS', 'APROVACAO', 'LIBERACAO', 'EM_EXECUCAO', 'ENCERRADA', 'ARQUIVADA', 'SUSPENSA', 'REJEITADA', name='estadopt', native_enum=False, length=40), nullable=True),
    sa.Column('estado_destino', sa.Enum('RASCUNHO', 'VALIDACAO', 'ANALISE_SMS', 'APROVACAO', 'LIBERACAO', 'EM_EXECUCAO', 'ENCERRADA', 'ARQUIVADA', 'SUSPENSA', 'REJEITADA', name='estadopt', native_enum=False, length=40), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('ocorrido_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispositivo', sa.String(length=120), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('geolocalizacao', sa.String(length=80), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=True),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_evento', sa.String(length=64), nullable=False),
    sa.Column('evento_compensado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ator_id'], ['usuario.id'], name=op.f('fk_audit_event_ator_id_usuario')),
    sa.ForeignKeyConstraint(['evento_compensado_id'], ['audit_event.id'], name=op.f('fk_audit_event_evento_compensado_id_audit_event')),
    sa.ForeignKeyConstraint(['pt_id'], ['permissao_trabalho.id'], name=op.f('fk_audit_event_pt_id_permissao_trabalho'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event')),
    sa.UniqueConstraint('hash_evento', name=op.f('uq_audit_event_hash_evento'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_ator_id'), ['ator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_ocorrido_em'), ['ocorrido_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_pt_id'), ['pt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_tipo_evento'), ['tipo_evento'], unique=False)

    op.create_table('pt_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['pt_id'], ['permissao_trabalho.id'], name=op.f('fk_pt_equipe_pt_id_permissao_trabalho'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_pt_equipe_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pt_equipe')),
    sa.UniqueConstraint('pt_id', 'usuario_id', name='uq_pt_equipe_pt_usuario')
    )
    with op.batch_alter_table('pt_equipe', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pt_equipe_pt_id'), ['pt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pt_equipe_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pt_versao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], name=op.f('fk_pt_versao_autor_id_usuario')),
    sa.ForeignKeyConstraint(['pt_id'], ['permissao_trabalho.id'], name=op.f('fk_pt_versao_pt_id_permissao_trabalho'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pt_versao')),
    sa.UniqueConstraint('pt_id', 'versao', name='uq_pt_versao_pt_versao')
    )
    with op.batch_alter_table('pt_versao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pt_versao_pt_id'), ['pt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pt_versao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pt_versao_pt_id'))

    op.drop_table('pt_versao')
    with op.batch_alter_table('pt_equipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pt_equipe_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pt_equipe_pt_id'))

    op.drop_table('pt_equipe')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_tipo_evento'))
        batch_op.drop_index(batch_op.f('ix_audit_event_pt_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_ocorrido_em'))
        batch_op.drop_index(batch_op.f('ix_audit_event_ator_id'))

    op.drop_table('audit_event')
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinatura_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_assinatura_pt_id'))

    op.drop_table('assinatura')
    with op.batch_alter_table('anexo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexo_pt_id'))

    op.drop_table('anexo')
    with op.batch_alter_table('permissao_trabalho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissao_trabalho_valida_ate'))
        batch_op.drop_index(batch_op.f('ix_permissao_trabalho_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_permissao_trabalho_requisitante_id'))
        batch_op.drop_index(batch_op.f('ix_permissao_trabalho_estado'))
        batch_op.drop_index(batch_op.f('ix_permissao_trabalho_area_id'))

    op.drop_table('permissao_trabalho')
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipamento_area_id'))

    op.drop_table('equipamento')
    with op.batch_alter_table('certificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificacao_valida_ate'))
        batch_op.drop_index(batch_op.f('ix_certificacao_usuario_id'))

    op.drop_table('certificacao')
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_area_unidade_id'))

    op.drop_table('area')
    op.drop_table('usuario')
    op.drop_table('unidade')
    op.drop_table('modelo_pt')
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerta_tipo'))
        batch_op.drop_index(batch_op.f('ix_alerta_status'))
        batch_op.drop_index(batch_op.f('ix_alerta_prazo'))

    op.drop_table('alerta')
    # ### end Alembic commands ###
