"""versao do formato de payload da trilha

Revision ID: 66f40a59708d
Revises: 126544508b16
Create Date: 2026-08-07 13:59:43.809659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f40a59708d'
down_revision: Union[str, Sequence[str], None] = '126544508b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versao_payload', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_column('versao_payload')

    # ### end Alembic commands ###
