"""elo unico por evento na trilha

Revision ID: ccddf73c09f2
Revises: 0517ef18c5d3
Create Date: 2026-08-09 16:55:56.815280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccddf73c09f2'
down_revision: Union[str, Sequence[str], None] = '0517ef18c5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_audit_event_elo', ['pt_id', 'hash_anterior'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audit_event_elo', type_='unique')

    # ### end Alembic commands ###
